---
version: '2'
services:
  watchtower:
    image: v2tec/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
  portainer:
    image: portainer/portainer
    container_name: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9000:9000"
    restart: unless-stopped
  airsonos:
    image: justintime/airsonos:latest
    container_name: airsonos
    network_mode: host
    ports:
      - "5000-5050"
    restart: unless-stopped
