---
version: '2'
services:
  watchtower:
    container_name: watchtower
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
  portainer:
    container_name: portainer
    image: portainer/portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9000:9000"
    restart: unless-stopped
  transmission:
    container_name: transmission
    image: haugene/transmission-openvpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      - /volume1/data/Transmission:/data
      - /volume1/download:/data/completed
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - openvpn.env
    environment:
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - LOCAL_NETWORK=192.168.128.0/24
      - TRANSMISSION_DOWNLOAD_QUEUE_SIZE=5
      - TRANSMISSION_SCRIPT_TORRENT_DONE_ENABLED=true
      - TRANSMISSION_SCRIPT_TORRENT_DONE_FILENAME=/data/remove.sh
      - TRANSMISSION_SPEED_LIMIT_UP=200
      - TRANSMISSION_SPEED_LIMIT_UP_ENABLED=true
      - TRANSMISSION_RATIO_LIMIT=0
      - TRANSMISSION_RATIO_LIMIT_ENABLED=true
    ports:
      - "9091:9091"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    restart: unless-stopped
  couchpotato:
    container_name: couchpotato
    image: linuxserver/couchpotato
    volumes:
      - /volume1/data/couchpotato:/config
      - /volume1/download/movies:/downloads
      - /volume1/video/movies:/movies
    environment:
      - TZ=Europe/Zurich
    ports:
      - "5054:5050"
    restart: unless-stopped
  sickrage:
    container_name: sickrage
    image: linuxserver/sickrage
    volumes:
      - /volume1/data/sickrage:/config
      - /volume1/download/series:/downloads
      - /volume1/video/series:/tv
    environment:
      - TZ=Europe/Zurich
    ports:
      - "8081:8081"
    restart: unless-stopped
  beets:
    container_name: beets
    image: linuxserver/beets
    volumes:
      - /volume1/data/beets:/config
      - /volume1/download:/downloads
      - /volume1/music:/music
    ports:
      - "8337:8337"
    restart: "no"
  headphones:
    container_name: headphones
    image: linuxserver/headphones
    volumes:
      - /volume1/data/headphones:/config
      - /volume1/download/music:/downloads
      - /volume1/music:/music
    environment:
      - TZ=Europe/Zurich
    ports:
      - "8182:8181"
    restart: unless-stopped
  resilio:
    container_name: resilio
    image: resilio/sync
    volumes:
      - /volume1/data/resilio-sync:/mnt/sync
      - /volume1/backup:/mnt/sync/folders
    ports:
      - "28888:28888"
      - "55555:55555"
    restart: unless-stopped
  plex:
    container_name: plex
    image: plexinc/pms-docker:plexpass
    network_mode: host
    volumes:
      - /volume1/data/Plex:/config
      - /volume1:/volume1
    env_file:
      - plex.env
    environment:
      - TZ=Europe/Zurich
  plexpy:
    container_name: plexpy
    image: linuxserver/plexpy
    volumes:
      - /volume1/data/PlexPy:/config
      - /volume1/data/Plex/Library/Application Support/Plex Media Server/Logs:/logs:ro
    environment:
      - TZ=Europe/Zurich
    ports:
      - "8181:8181"
